module.exports = {
    "fr": {
        "lang_code": "fr",
        "cv_link": "img/CV - Simon BONNIER.pdf",
        "form_submit_alert": "Merci ! Dans une version finale, ce formulaire sera relie a une adresse email ou une base de donnees.",
        "txt_simon_bonnier_portfolio_but_techniques_commercialisation": "Simon Bonnier - Portfolio BUT Techniques de Commercialisation",
        "txt_s": "S",
        "txt_bonnier": ".Bonnier",
        "txt_accueil": "Accueil",
        "txt_propos": "À propos",
        "txt_competences": "Compétences",
        "txt_experiences_projets": "Expériences & Projets",
        "txt_contact": "Contact",
        "txt_bonjour_suis": "Bonjour, je suis",
        "txt_simon": "Simon",
        "txt_bonnier_2": "Bonnier",
        "txt_etudiant_but_techniques_commercialisation": "Étudiant en BUT Techniques de Commercialisation",
        "txt_passionne_par_relation_client_negociation_strategie": "Passionné par la relation client, la négociation et la stratégie commerciale. À la recherche de nouveaux défis pour construire un management global et performant.",
        "txt_decouvrir_portfolio": "Découvrir mon portfolio",
        "txt_me_contacter": "Me contacter",
        "txt_parcours": "Parcours",
        "txt_but_techniques_commercialisation_3eme_annee": "BUT Techniques de Commercialisation - 3ème année",
        "txt_specialisation_business_developpement_relation_client": "Spécialisation business développement de la relation client",
        "txt_profil": "Mon Profil",
        "txt_propos_moi": "À propos de moi",
        "txt_theorie_pratique": "De la théorie à la pratique",
        "txt_actuellement": "Actuellement en",
        "txt_but_techniques_commercialisation": "BUT Techniques de Commercialisation",
        "txt_l_iut_jean_monnet_saint_etienne": "à l'IUT Jean Monnet de Saint-Étienne, j'acquiers une solide expertise en négociation, en gestion de la relation client et en analyse de marchés.",
        "txt_premiere_experience_milieu_bancaire_credit_agricole": "Une première expérience en milieu bancaire (Crédit Agricole) m'a offert une vision très concrète des enjeux financiers et économiques, tant pour les entreprises que pour les particuliers. Calme, réfléchi et passionné de sport, j'applique la rigueur et la motivation acquises au quotidien dans mes projets professionnels.",
        "txt_projet_professionnel": "Mon Projet Professionnel",
        "txt_ambition_est_d_integrer": "Mon ambition est d'intégrer un",
        "txt_programme_grande_ecole": "Programme Grande École",
        "txt_approfondir_connaissances_strategie_finance_ainsi_developper": "pour approfondir mes connaissances en stratégie et en finance, et ainsi développer une vision plus globale du management.",
        "txt_telecharger_cv": "Télécharger mon CV",
        "txt_localisation": "Localisation",
        "txt_lyon_france": "Lyon, France",
        "txt_mobilite": "Mobilité",
        "txt_permis_b": "Permis B",
        "txt_telephone": "Téléphone",
        "txt_07_69_48_36_98": "07 69 48 36 98",
        "txt_email": "Email",
        "txt_simon_bonnier5_gmail_com": "simon.bonnier5@gmail.com",
        "txt_savoir_faire_savoir_etre": "Savoir-faire & Savoir-être",
        "txt_competences_2": "Mes Compétences",
        "txt_conduire_actions_marketing_participer_strategie": "Conduire les actions marketing &amp; Participer à la stratégie",
        "txt_analyse_l_environnement_etudes_marche_elaboration": "Analyse de l'environnement, études de marché, élaboration de mix et détection d'opportunités.",
        "txt_analyse_marche": "Analyse de marché",
        "txt_veille_concurrentielle": "Veille concurrentielle",
        "txt_strategie_positionnement": "Stratégie de positionnement",
        "txt_vendre_offre_manager_relation_client": "Vendre une offre &amp; Manager la relation client",
        "txt_negociation_commerciale_developpement_culture_service_client": "Négociation commerciale, développement de la culture service client, pilotage de la satisfaction.",
        "txt_negociation_commerciale": "Négociation commerciale",
        "txt_gestion_relation_client_crm": "Gestion relation client (CRM)",
        "txt_traitement_objections": "Traitement des objections",
        "txt_communiquer_l_offre_commerciale": "Communiquer l'offre commerciale",
        "txt_structuration_plans_communication_strategies_digitales_creation": "Structuration de plans de communication, stratégies digitales et création de supports.",
        "txt_plan_communication": "Plan de communication",
        "txt_strategie_digitale": "Stratégie digitale",
        "txt_creation_supports": "Création de supports",
        "txt_axes_d_amelioration": "Mes axes d'amélioration",
        "txt_afin_valider_pleinement_competences_niveau_3": "Afin de valider pleinement les compétences de niveau 3 en Business Développement, je dois encore approfondir ma maîtrise des achats complexes en B2B. Mon objectif d'ici la fin de l'année est de mener une négociation complète avec un fournisseur dans le cadre de mon alternance.",
        "txt_competences_comportementales_soft_skills": "Compétences Comportementales (Soft Skills)",
        "txt_qualites_humaines_qui_font_difference_quotidien": "Les qualités humaines qui font la différence au quotidien.",
        "txt_rigueur": "Rigueur",
        "txt_sens_relationnel": "Sens du relationnel",
        "txt_travail_d_equipe": "Travail d'équipe",
        "txt_adaptabilite": "Adaptabilité",
        "txt_autonomie": "Autonomie",
        "txt_organisation": "Organisation",
        "txt_parcours_2": "Mon Parcours",
        "txt_analyse_experiences_professionnelles_academiques_selon_methode": "Analyse de mes expériences professionnelles et académiques selon la méthode attendue pour l'évaluation des compétences (Contexte, Objectifs, Actions, Résultats).",
        "txt_sept_2025_cours": "Sept 2025 - En cours",
        "txt_attache_clientele": "Attaché Clientèle",
        "txt_credit_agricole_centre_est_alternance": "Crédit Agricole Centre-Est (Alternance)",
        "txt_developper_fidelisation_rebond_commercial_agence_avec": "Développer la fidélisation et le rebond commercial en agence, avec une posture de conseil durable.",
        "txt_analyser_cette_experience": "Analyser cette expérience",
        "txt_fevrier_2025": "Février 2025",
        "txt_projet_academique_creasim": "Projet Académique : CREASIM",
        "txt_simulation_commerciale_iut": "Simulation Commerciale (IUT)",
        "txt_construire_strategie_commerciale_equipe_sous_contrainte": "Construire une stratégie commerciale en équipe sous contrainte de budget et de temps.",
        "txt_fev_2024_juin_2025": "Fév 2024 - Juin 2025",
        "txt_equipier_polyvalent": "Équipier Polyvalent",
        "txt_mcdonald_s_cdi_etudiant": "McDonald's (CDI Étudiant)",
        "txt_garantir_service_rapide_conforme_normes_malgre": "Garantir un service rapide et conforme aux normes malgré l'intensité des rushs.",
        "txt_2021_2023": "2021 - 2023",
        "txt_engagements_associatifs": "Engagements Associatifs",
        "txt_service_national_universel_snu": "Service National Universel (SNU)",
        "txt_s_engager_missions_citoyennes_logistiques_avec": "S'engager sur des missions citoyennes et logistiques avec impact terrain.",
        "txt_formations_academiques": "Formations Académiques",
        "txt_iut_jean_monnet_st_etienne": "IUT Jean Monnet, St-Étienne",
        "txt_2023_present": "2023 - Présent",
        "txt_baccalaureat_general": "Baccalauréat Général",
        "txt_lycee_rene_descartes_mention_ab": "Lycée René Descartes (Mention AB)",
        "txt_2020_2023": "2020 - 2023",
        "txt_credit_agricole_analyse_reflexive": "Crédit Agricole — Analyse réflexive",
        "txt_bloc_1_cadre": "Bloc 1 · Le Cadre",
        "txt_contexte": "Contexte :",
        "txt_alternance_agence_entretiens_face_face_appels": "Alternance en agence, entretiens en face-à-face et appels sortants, travail en binôme avec le conseiller référent.",
        "txt_objectifs_enjeux": "Objectifs &amp; enjeux :",
        "txt_fideliser_clients_contribuer_objectifs_commerciaux_mensuels": "Fidéliser les clients et contribuer aux objectifs commerciaux mensuels de l'agence sur l'épargne et l'équipement.",
        "txt_bloc_2_l_action": "Bloc 2 · L'Action",
        "txt_j_ai_prepare_plans_decouverte_avant": "J'ai préparé des plans de découverte avant chaque rendez-vous. Ensuite, j'ai utilisé l'OAV pour argumenter les solutions. Enfin, j'ai pratiqué le rebond commercial pour proposer une offre complémentaire cohérente.",
        "txt_bloc_3_bilan": "Bloc 3 · Le Bilan",
        "txt_resultats": "Résultats :",
        "txt_18_rendez_transformes_2_mois_retours": "+18% de rendez-vous transformés sur 2 mois, retours positifs sur la clarté des explications clients.",
        "txt_difficultes_auto_evaluation": "Difficultés &amp; auto-évaluation :",
        "txt_objections_prix_certains_produits_aujourd_hui": "Objections prix sur certains produits ; aujourd'hui, je structurerais davantage mes relances post-rendez-vous et je dois encore progresser sur les ventes croisées complexes.",
        "txt_bloc_4_competences_ressources": "Bloc 4 · Compétences &amp; ressources",
        "txt_ressources_mobilisees_r3_02_entretien_vente": "Ressources mobilisées : R3.02 Entretien de vente, R4.02 Négociation. Compétences BUT validées : « Vendre une offre &amp; manager la relation client » (Niveau 2), « Communiquer l'offre » (Niveau 2).",
        "txt_bloc_5_preuves": "Bloc 5 · Les preuves",
        "txt_capture_anonymisee_crm_bancaire": "Capture anonymisée du CRM bancaire",
        "txt_trace_suivis_clients_relances_planifiees": "Trace des suivis clients et des relances planifiées.",
        "txt_valide_competence_pilotage_relation_client": "Valide la compétence de pilotage de la relation client.",
        "txt_grille_suivi_objectifs_agence": "Grille de suivi des objectifs agence",
        "txt_comparatif_objectifs_realisations_avec_indicateurs_hebdomadaires": "Comparatif objectifs/réalisations avec indicateurs hebdomadaires.",
        "txt_valide_competence_d_analyse_commerciale_reporting": "Valide la compétence d'analyse commerciale et de reporting.",
        "txt_projet_creasim_analyse_reflexive": "Projet CREASIM — Analyse réflexive",
        "txt_simulation_commerciale_equipe_5_budget_fictif": "Simulation commerciale en équipe de 5, budget fictif, délais contraints sur 4 semaines.",
        "txt_construire_offre_coherente_defendre_choix_strategiques": "Construire une offre cohérente et défendre des choix stratégiques réalistes face au jury.",
        "txt_j_ai_coordonne_l_equipe_planning": "J'ai coordonné l'équipe sur un planning partagé. D'abord, j'ai analysé le marché ; ensuite, j'ai élaboré la stratégie marketing (ciblage/positionnement) ; puis, j'ai structuré le plan de communication et le pitch final.",
        "txt_2e_place_promotion_note_orale_16": "2e place de la promotion, note orale 16/20, appréciation de la cohérence stratégique.",
        "txt_arbitrages_budgetaires_complexes_aujourd_hui_renforcerais": "Arbitrages budgétaires complexes ; aujourd'hui je renforcerais l'analyse de sensibilité financière.",
        "txt_ressources_mobilisees_r3_04_etudes_marketing": "Ressources mobilisées : R3.04 Études marketing, SAÉ stratégie commerciale, techniques de communication digitale. Compétences BUT validées : marketing (Niveau 2), communication commerciale (Niveau 2), gestion de projet (Niveau 2).",
        "txt_pdf_presentation_finale": "PDF de la présentation finale",
        "txt_synthese_ciblage_positionnement_recommandations": "Synthèse du ciblage, positionnement et recommandations.",
        "txt_valide_competence_communiquer_l_offre_commerciale": "Valide la compétence « communiquer l'offre commerciale ».",
        "txt_excel_budget_previsionnel": "Excel du budget prévisionnel",
        "txt_tableau_investissements_marges_hypotheses": "Tableau des investissements, marges et hypothèses.",
        "txt_valide_competence_d_analyse_pilotage_marketing": "Valide la compétence d'analyse et de pilotage marketing.",
        "txt_photo_d_equipe_lors_pitch": "Photo d'équipe lors du pitch",
        "txt_moment_soutenance_repartition_roles_l_oral": "Moment de soutenance et répartition des rôles à l'oral.",
        "txt_valide_competence_coordination_collective": "Valide la compétence de coordination collective.",
        "txt_mcdonald_s_analyse_reflexive": "McDonald's — Analyse réflexive",
        "txt_cdi_etudiant_restaurant_fort_flux_travail": "CDI étudiant en restaurant à fort flux, travail en équipe polyvalente.",
        "txt_assurer_satisfaction_client_immediate_respect_strict": "Assurer la satisfaction client immédiate et le respect strict des normes d'hygiène.",
        "txt_j_ai_organise_priorites_production_pendant": "J'ai organisé les priorités de production pendant les rushs. Ensuite, j'ai coordonné les postes caisse/cuisine. J'ai contrôlé les procédures HACCP et j'ai accompagné les nouveaux équipiers sur les standards.",
        "txt_diminution_temps_d_attente_observes_pointe": "Diminution des temps d'attente observés en pointe, retours clients positifs sur la rapidité.",
        "txt_gestion_stress_lors_rushs_dois_encore": "Gestion du stress lors des rushs ; je dois encore gagner en anticipation sur les ruptures produits.",
        "txt_competences_acquises_travail_equipe_resilience_management": "Compétences acquises : travail en équipe, résilience, management opérationnel. Ressources IUT mobilisées : communication interpersonnelle, gestion de la qualité de service, techniques de coordination.",
        "txt_planning_d_equipe_semaine_rush": "Planning d'équipe semaine de rush",
        "txt_organisation_postes_absorber_pics_d_activite": "Organisation des postes pour absorber les pics d'activité.",
        "txt_valide_competence_management_operationnel": "Valide la compétence de management opérationnel.",
        "txt_checklist_hygiene_securite": "Checklist hygiène et sécurité",
        "txt_suivi_controles_haccp_realises_service": "Suivi des contrôles HACCP réalisés en service.",
        "txt_valide_competence_rigueur_process_qualite": "Valide la compétence de rigueur process et qualité.",
        "txt_snu_analyse_reflexive": "SNU — Analyse réflexive",
        "txt_engagement_citoyen_plusieurs_evenements_solidaires_sportifs": "Engagement citoyen sur plusieurs événements solidaires et sportifs, interventions en équipe.",
        "txt_assurer_logistique_fluide_accueil_qualitatif_public": "Assurer une logistique fluide et un accueil qualitatif du public.",
        "txt_j_ai_planifie_repartition_taches_benevoles": "J'ai planifié la répartition des tâches bénévoles. Ensuite, j'ai géré les flux participants et les stocks terrain. Enfin, j'ai communiqué avec les organisateurs pour ajuster en temps réel.",
        "txt_evenements_tenus_sans_incident_majeur_feedback": "Événements tenus sans incident majeur, feedback positif sur l'accueil.",
        "txt_besoin_mieux_anticiper_imprevus_meteo_souhaite": "Besoin de mieux anticiper les imprévus météo ; je souhaite structurer davantage mes plans de contingence.",
        "txt_competences_validees_organisation_communication_engagement_collectif": "Compétences validées : organisation, communication, engagement collectif (Niveau 1 à 2). Ressources mobilisées : techniques d'animation commerciale et gestion événementielle.",
        "txt_photo_terrain_mission_solidaire": "Photo terrain mission solidaire",
        "txt_illustration_taches_logistiques_realisees_avec_l": "Illustration des tâches logistiques réalisées avec l'équipe.",
        "txt_valide_competence_d_organisation_operationnelle": "Valide la compétence d'organisation opérationnelle.",
        "txt_grille_d_evaluation_d_engagement": "Grille d'évaluation d'engagement",
        "txt_retour_encadrant_posture_fiabilite": "Retour encadrant sur la posture et la fiabilité.",
        "txt_valide_competence_collaboration_citoyenne": "Valide la compétence de collaboration citoyenne.",
        "txt_echangeons": "Échangeons",
        "txt_contactez_moi": "Contactez-moi",
        "txt_si_profil_interesse_collaboration_alternance_ou": "Si mon profil vous intéresse pour une collaboration, une alternance ou un échange, n'hésitez pas à m'envoyer un message.",
        "txt_nom_complet": "Nom complet",
        "txt_adresse_email": "Adresse email",
        "txt_message": "Message",
        "txt_envoyer_message": "Envoyer le message",
        "txt_portfolio_but_techniques_commercialisation_annee_2025": "Portfolio BUT Techniques de Commercialisation - Année 2025",
        "txt_linkedin": "LinkedIn",
        "txt_copy": "&copy;",
        "txt_simon_bonnier_tous_droits_reserves": "Simon Bonnier. Tous droits réservés.",
        "attr_ouvrir_menu": "Ouvrir le menu",
        "attr_simon_bonnier": "Simon Bonnier",
        "attr_logo_credit_agricole": "Logo Crédit Agricole",
        "attr_logo_mcdonald_s": "Logo McDonald's",
        "attr_logo_service_national_universel": "Logo Service National Universel",
        "attr_logo_universite_jean_monnet_saint_etienne": "Logo Université Jean Monnet Saint-Étienne",
        "attr_votre_nom": "Votre nom",
        "attr_exemple_com": "vous@exemple.com",
        "attr_votre_message": "Votre message...",
        "lang_toggle_href": "en/",
        "txt_lang_toggle": "FR / EN",
        "attr_switch_language": "Changer la langue",
        "attr_flag_fr": "Drapeau francais",
        "attr_flag_gb": "Drapeau anglais",
        "txt_experiences_professionnelles": "Experiences Professionnelles",
        "txt_projets_engagements": "Projets & Engagements",
        "txt_copy_email_button": "Copier",
        "txt_copied_email_button": "Copie !",
        "attr_copy_email": "Copier l adresse email",
        "txt_contact_linkedin": "Me contacter sur LinkedIn",
        "attr_send_email": "Envoyer un email"
    },
    "en": {
        "lang_code": "en",
        "cv_link": "../img/CV - Simon BONNIER.pdf",
        "form_submit_alert": "Thank you! In a final version, this form will be connected to an email address or a database.",
        "txt_simon_bonnier_portfolio_but_techniques_commercialisation": "Simon Bonnier - Business and Marketing Technology Degree Portfolio",
        "txt_s": "S",
        "txt_bonnier": ".Bonnier",
        "txt_accueil": "Home",
        "txt_propos": "About",
        "txt_competences": "Skills",
        "txt_experiences_projets": "Experience & Projects",
        "txt_contact": "Contact",
        "txt_bonjour_suis": "Hello, I am",
        "txt_simon": "Simon",
        "txt_bonnier_2": "Bonnier",
        "txt_etudiant_but_techniques_commercialisation": "Student in a Business and Marketing Technology Degree",
        "txt_passionne_par_relation_client_negociation_strategie": "Passionate about customer relationships, negotiation, and business strategy. Looking for new challenges to build strong, well-rounded management skills.",
        "txt_decouvrir_portfolio": "Discover my portfolio",
        "txt_me_contacter": "Contact me",
        "txt_parcours": "Background",
        "txt_but_techniques_commercialisation_3eme_annee": "Business and Marketing Technology Degree - 3rd year",
        "txt_specialisation_business_developpement_relation_client": "Specialization in business development and customer relationship management",
        "txt_profil": "My Profile",
        "txt_propos_moi": "About me",
        "txt_theorie_pratique": "From theory to practice",
        "txt_actuellement": "Currently in",
        "txt_but_techniques_commercialisation": "Business and Marketing Technology Degree",
        "txt_l_iut_jean_monnet_saint_etienne": "at IUT Jean Monnet in Saint-Etienne, I am developing solid expertise in negotiation, customer relationship management, and market analysis.",
        "txt_premiere_experience_milieu_bancaire_credit_agricole": "An initial experience in banking (Credit Agricole) gave me a concrete understanding of financial and economic challenges for both companies and individuals. Calm, thoughtful, and passionate about sports, I apply discipline and motivation daily in my professional projects.",
        "txt_projet_professionnel": "My Career Plan",
        "txt_ambition_est_d_integrer": "My ambition is to join a",
        "txt_programme_grande_ecole": "Grande Ecole Program",
        "txt_approfondir_connaissances_strategie_finance_ainsi_developper": "to deepen my knowledge in strategy and finance and develop a broader view of management.",
        "txt_telecharger_cv": "Download my resume",
        "txt_localisation": "Location",
        "txt_lyon_france": "Lyon, France",
        "txt_mobilite": "Mobility",
        "txt_permis_b": "Driving license (Category B)",
        "txt_telephone": "Phone",
        "txt_07_69_48_36_98": "07 69 48 36 98",
        "txt_email": "Email",
        "txt_simon_bonnier5_gmail_com": "simon.bonnier5@gmail.com",
        "txt_savoir_faire_savoir_etre": "Hard Skills & Soft Skills",
        "txt_competences_2": "My Skills",
        "txt_conduire_actions_marketing_participer_strategie": "Lead marketing actions & contribute to strategy",
        "txt_analyse_l_environnement_etudes_marche_elaboration": "Environmental analysis, market research, marketing mix design, and opportunity detection.",
        "txt_analyse_marche": "Market analysis",
        "txt_veille_concurrentielle": "Competitive intelligence",
        "txt_strategie_positionnement": "Positioning strategy",
        "txt_vendre_offre_manager_relation_client": "Sell an offer & manage customer relationships",
        "txt_negociation_commerciale_developpement_culture_service_client": "Sales negotiation, customer-service culture development, and satisfaction management.",
        "txt_negociation_commerciale": "Sales negotiation",
        "txt_gestion_relation_client_crm": "Customer relationship management (CRM)",
        "txt_traitement_objections": "Objection handling",
        "txt_communiquer_l_offre_commerciale": "Communicate the commercial offer",
        "txt_structuration_plans_communication_strategies_digitales_creation": "Communication plan structuring, digital strategies, and asset creation.",
        "txt_plan_communication": "Communication plan",
        "txt_strategie_digitale": "Digital strategy",
        "txt_creation_supports": "Asset creation",
        "txt_axes_d_amelioration": "Areas for improvement",
        "txt_afin_valider_pleinement_competences_niveau_3": "To fully validate level-3 Business Development skills, I still need to deepen my mastery of complex B2B purchasing. My goal by the end of the year is to lead a complete supplier negotiation during my work-study program.",
        "txt_competences_comportementales_soft_skills": "Behavioral Skills (Soft Skills)",
        "txt_qualites_humaines_qui_font_difference_quotidien": "The human qualities that make a difference every day.",
        "txt_rigueur": "Discipline",
        "txt_sens_relationnel": "Interpersonal skills",
        "txt_travail_d_equipe": "Teamwork",
        "txt_adaptabilite": "Adaptability",
        "txt_autonomie": "Autonomy",
        "txt_organisation": "Organization",
        "txt_parcours_2": "My Journey",
        "txt_analyse_experiences_professionnelles_academiques_selon_methode": "Analysis of my professional and academic experiences using the expected competency-evaluation method (Context, Objectives, Actions, Results).",
        "txt_sept_2025_cours": "Sept 2025 - Present",
        "txt_attache_clientele": "Client Advisor",
        "txt_credit_agricole_centre_est_alternance": "Credit Agricole Centre-Est (Work-study)",
        "txt_developper_fidelisation_rebond_commercial_agence_avec": "Develop customer loyalty and cross-selling in branch, with a long-term advisory approach.",
        "txt_analyser_cette_experience": "Analyze this experience",
        "txt_fevrier_2025": "February 2025",
        "txt_projet_academique_creasim": "Academic Project: CREASIM",
        "txt_simulation_commerciale_iut": "Sales Simulation (IUT)",
        "txt_construire_strategie_commerciale_equipe_sous_contrainte": "Build a team sales strategy under budget and time constraints.",
        "txt_fev_2024_juin_2025": "Feb 2024 - June 2025",
        "txt_equipier_polyvalent": "Versatile Crew Member",
        "txt_mcdonald_s_cdi_etudiant": "McDonald's (Student permanent contract)",
        "txt_garantir_service_rapide_conforme_normes_malgre": "Ensure fast service and compliance with standards despite peak rush intensity.",
        "txt_2021_2023": "2021 - 2023",
        "txt_engagements_associatifs": "Community Engagement",
        "txt_service_national_universel_snu": "National Universal Service (SNU)",
        "txt_s_engager_missions_citoyennes_logistiques_avec": "Take part in civic and logistics missions with field impact.",
        "txt_formations_academiques": "Academic Education",
        "txt_iut_jean_monnet_st_etienne": "IUT Jean Monnet, Saint-Etienne",
        "txt_2023_present": "2023 - Present",
        "txt_baccalaureat_general": "General Baccalaureate",
        "txt_lycee_rene_descartes_mention_ab": "Rene Descartes High School (Honors)",
        "txt_2020_2023": "2020 - 2023",
        "txt_credit_agricole_analyse_reflexive": "Credit Agricole - Reflective Analysis",
        "txt_bloc_1_cadre": "Block 1 - Framework",
        "txt_contexte": "Context:",
        "txt_alternance_agence_entretiens_face_face_appels": "Work-study in branch, face-to-face interviews and outbound calls, working in tandem with the reference advisor.",
        "txt_objectifs_enjeux": "Objectives & stakes:",
        "txt_fideliser_clients_contribuer_objectifs_commerciaux_mensuels": "Build customer loyalty and contribute to the branch monthly sales objectives on savings and equipment products.",
        "txt_bloc_2_l_action": "Block 2 - Action",
        "txt_j_ai_prepare_plans_decouverte_avant": "I prepared discovery plans before each meeting. Then I used OAV to structure arguments. Finally, I used commercial rebound to propose a coherent complementary offer.",
        "txt_bloc_3_bilan": "Block 3 - Review",
        "txt_resultats": "Results:",
        "txt_18_rendez_transformes_2_mois_retours": "+18% increase in converted meetings over 2 months, with positive feedback on clarity of customer explanations.",
        "txt_difficultes_auto_evaluation": "Difficulties & self-assessment:",
        "txt_objections_prix_certains_produits_aujourd_hui": "Price objections on some products; today, I would better structure my post-meeting follow-ups and I still need to improve on complex cross-selling.",
        "txt_bloc_4_competences_ressources": "Block 4 - Skills & resources",
        "txt_ressources_mobilisees_r3_02_entretien_vente": "Resources used: R3.02 Sales Interview, R4.02 Negotiation. Validated skills: \"Sell an offer & manage customer relationships\" (Level 2), \"Communicate the offer\" (Level 2).",
        "txt_bloc_5_preuves": "Block 5 - Evidence",
        "txt_capture_anonymisee_crm_bancaire": "Anonymized banking CRM screenshot",
        "txt_trace_suivis_clients_relances_planifiees": "Traceability of customer follow-ups and planned callbacks.",
        "txt_valide_competence_pilotage_relation_client": "Validates customer relationship management skills.",
        "txt_grille_suivi_objectifs_agence": "Branch objective tracking grid",
        "txt_comparatif_objectifs_realisations_avec_indicateurs_hebdomadaires": "Objectives vs achievements comparison with weekly indicators.",
        "txt_valide_competence_d_analyse_commerciale_reporting": "Validates commercial analysis and reporting skills.",
        "txt_projet_creasim_analyse_reflexive": "CREASIM Project - Reflective Analysis",
        "txt_simulation_commerciale_equipe_5_budget_fictif": "Team sales simulation with 5 members, fictional budget, and tight 4-week deadlines.",
        "txt_construire_offre_coherente_defendre_choix_strategiques": "Build a coherent offer and defend realistic strategic choices before the jury.",
        "txt_j_ai_coordonne_l_equipe_planning": "I coordinated the team through a shared schedule. First, I analyzed the market; then I designed the marketing strategy (targeting/positioning); finally, I structured the communication plan and the final pitch.",
        "txt_2e_place_promotion_note_orale_16": "2nd place in the cohort, oral grade 16/20, praised for strategic coherence.",
        "txt_arbitrages_budgetaires_complexes_aujourd_hui_renforcerais": "Complex budget trade-offs; today I would reinforce financial sensitivity analysis.",
        "txt_ressources_mobilisees_r3_04_etudes_marketing": "Resources used: R3.04 Marketing Studies, SAE commercial strategy, digital communication techniques. Validated skills: marketing (Level 2), commercial communication (Level 2), project management (Level 2).",
        "txt_pdf_presentation_finale": "Final presentation PDF",
        "txt_synthese_ciblage_positionnement_recommandations": "Summary of targeting, positioning, and recommendations.",
        "txt_valide_competence_communiquer_l_offre_commerciale": "Validates the skill \"communicate the commercial offer\".",
        "txt_excel_budget_previsionnel": "Forecast budget spreadsheet",
        "txt_tableau_investissements_marges_hypotheses": "Table of investments, margins, and assumptions.",
        "txt_valide_competence_d_analyse_pilotage_marketing": "Validates analysis and marketing steering skills.",
        "txt_photo_d_equipe_lors_pitch": "Team photo during pitch",
        "txt_moment_soutenance_repartition_roles_l_oral": "Presentation moment and role distribution during oral defense.",
        "txt_valide_competence_coordination_collective": "Validates collective coordination skills.",
        "txt_mcdonald_s_analyse_reflexive": "McDonald's - Reflective Analysis",
        "txt_cdi_etudiant_restaurant_fort_flux_travail": "Student permanent contract in a high-traffic restaurant, working in a versatile team.",
        "txt_assurer_satisfaction_client_immediate_respect_strict": "Ensure immediate customer satisfaction and strict hygiene standard compliance.",
        "txt_j_ai_organise_priorites_production_pendant": "I organized production priorities during rushes. Then I coordinated cash/kitchen stations. I monitored HACCP procedures and coached new crew members on standards.",
        "txt_diminution_temps_d_attente_observes_pointe": "Reduced observed waiting times at peak hours, with positive customer feedback on speed.",
        "txt_gestion_stress_lors_rushs_dois_encore": "Stress management during rushes; I still need to improve anticipation of stock shortages.",
        "txt_competences_acquises_travail_equipe_resilience_management": "Skills gained: teamwork, resilience, operational management. IUT resources used: interpersonal communication, service-quality management, coordination techniques.",
        "txt_planning_d_equipe_semaine_rush": "Team schedule for rush week",
        "txt_organisation_postes_absorber_pics_d_activite": "Station organization to absorb activity peaks.",
        "txt_valide_competence_management_operationnel": "Validates operational management skills.",
        "txt_checklist_hygiene_securite": "Hygiene and safety checklist",
        "txt_suivi_controles_haccp_realises_service": "Tracking of HACCP checks performed during service.",
        "txt_valide_competence_rigueur_process_qualite": "Validates process discipline and quality skills.",
        "txt_snu_analyse_reflexive": "SNU - Reflective Analysis",
        "txt_engagement_citoyen_plusieurs_evenements_solidaires_sportifs": "Civic engagement across multiple solidarity and sports events, with team interventions.",
        "txt_assurer_logistique_fluide_accueil_qualitatif_public": "Ensure smooth logistics and high-quality public reception.",
        "txt_j_ai_planifie_repartition_taches_benevoles": "I planned volunteer task allocation. Then I managed participant flow and on-site stock. Finally, I communicated with organizers to adjust in real time.",
        "txt_evenements_tenus_sans_incident_majeur_feedback": "Events delivered without major incidents, with positive feedback on reception.",
        "txt_besoin_mieux_anticiper_imprevus_meteo_souhaite": "Need to better anticipate weather-related contingencies; I want to structure contingency plans further.",
        "txt_competences_validees_organisation_communication_engagement_collectif": "Validated skills: organization, communication, collective engagement (Level 1 to 2). Resources used: commercial facilitation and event management techniques.",
        "txt_photo_terrain_mission_solidaire": "Field photo - solidarity mission",
        "txt_illustration_taches_logistiques_realisees_avec_l": "Illustration of logistics tasks carried out with the team.",
        "txt_valide_competence_d_organisation_operationnelle": "Validates operational organization skills.",
        "txt_grille_d_evaluation_d_engagement": "Engagement assessment grid",
        "txt_retour_encadrant_posture_fiabilite": "Supervisor feedback on attitude and reliability.",
        "txt_valide_competence_collaboration_citoyenne": "Validates civic collaboration skills.",
        "txt_echangeons": "Let us connect",
        "txt_contactez_moi": "Contact me",
        "txt_si_profil_interesse_collaboration_alternance_ou": "If my profile interests you for a collaboration, work-study opportunity, or discussion, feel free to send me a message.",
        "txt_nom_complet": "Full name",
        "txt_adresse_email": "Email address",
        "txt_message": "Message",
        "txt_envoyer_message": "Send message",
        "txt_portfolio_but_techniques_commercialisation_annee_2025": "Business and Marketing Technology Degree Portfolio - Year 2025",
        "txt_linkedin": "LinkedIn",
        "txt_copy": "&copy;",
        "txt_simon_bonnier_tous_droits_reserves": "Simon Bonnier. All rights reserved.",
        "attr_ouvrir_menu": "Open menu",
        "attr_simon_bonnier": "Simon Bonnier",
        "attr_logo_credit_agricole": "Credit Agricole logo",
        "attr_logo_mcdonald_s": "McDonald's logo",
        "attr_logo_service_national_universel": "National Universal Service logo",
        "attr_logo_universite_jean_monnet_saint_etienne": "Jean Monnet University logo",
        "attr_votre_nom": "Your name",
        "attr_exemple_com": "you@example.com",
        "attr_votre_message": "Your message...",
        "lang_toggle_href": "../",
        "txt_lang_toggle": "FR / EN",
        "attr_switch_language": "Switch language",
        "attr_flag_fr": "French flag",
        "attr_flag_gb": "British flag",
        "txt_experiences_professionnelles": "Professional Experience",
        "txt_projets_engagements": "Projects & Engagements",
        "txt_copy_email_button": "Copy",
        "txt_copied_email_button": "Copied!",
        "attr_copy_email": "Copy email address",
        "txt_contact_linkedin": "Contact me on LinkedIn",
        "attr_send_email": "Send email"
    }
};
