module.exports = {
    "fr": {
        "lang_code": "fr",
        "cv_link": "img/CV - Simon BONNIER.pdf",
        "form_submit_alert": "Merci ! Dans une version finale, ce formulaire sera relie a une adresse email ou une base de donnees.",
        "text_001": "Simon Bonnier - Portfolio BUT Techniques de Commercialisation",
        "text_002": "S",
        "text_003": ".Bonnier",
        "text_004": "Accueil",
        "text_005": "À propos",
        "text_006": "Compétences",
        "text_007": "Expériences & Projets",
        "text_008": "Contact",
        "text_009": "Bonjour, je suis",
        "text_010": "Simon",
        "text_011": "Bonnier",
        "text_012": "Étudiant en BUT Techniques de Commercialisation",
        "text_013": "Passionné par la relation client, la négociation et la stratégie commerciale. À la recherche de nouveaux défis pour construire un management global et performant.",
        "text_014": "Découvrir mon portfolio",
        "text_015": "Me contacter",
        "text_016": "Parcours",
        "text_017": "BUT Techniques de Commercialisation - 3ème année",
        "text_018": "Spécialisation business développement de la relation client",
        "text_019": "Mon Profil",
        "text_020": "À propos de moi",
        "text_021": "De la théorie à la pratique",
        "text_022": "Actuellement en",
        "text_023": "BUT Techniques de Commercialisation",
        "text_024": "à l'IUT Jean Monnet de Saint-Étienne, j'acquiers une solide expertise en négociation, en gestion de la relation client et en analyse de marchés.",
        "text_025": "Une première expérience en milieu bancaire (Crédit Agricole) m'a offert une vision très concrète des enjeux financiers et économiques, tant pour les entreprises que pour les particuliers. Calme, réfléchi et passionné de sport, j'applique la rigueur et la motivation acquises au quotidien dans mes projets professionnels.",
        "text_026": "Mon Projet Professionnel",
        "text_027": "Mon ambition est d'intégrer un",
        "text_028": "Programme Grande École",
        "text_029": "pour approfondir mes connaissances en stratégie et en finance, et ainsi développer une vision plus globale du management.",
        "text_030": "Télécharger mon CV",
        "text_031": "Localisation",
        "text_032": "Lyon, France",
        "text_033": "Mobilité",
        "text_034": "Permis B",
        "text_035": "Téléphone",
        "text_036": "07 69 48 36 98",
        "text_037": "Email",
        "text_038": "simon.bonnier5@gmail.com",
        "text_039": "Savoir-faire & Savoir-être",
        "text_040": "Mes Compétences",
        "text_041": "Conduire les actions marketing &amp; Participer à la stratégie",
        "text_042": "Analyse de l'environnement, études de marché, élaboration de mix et détection d'opportunités.",
        "text_043": "Analyse de marché",
        "text_044": "Veille concurrentielle",
        "text_045": "Stratégie de positionnement",
        "text_046": "Vendre une offre &amp; Manager la relation client",
        "text_047": "Négociation commerciale, développement de la culture service client, pilotage de la satisfaction.",
        "text_048": "Négociation commerciale",
        "text_049": "Gestion relation client (CRM)",
        "text_050": "Traitement des objections",
        "text_051": "Communiquer l'offre commerciale",
        "text_052": "Structuration de plans de communication, stratégies digitales et création de supports.",
        "text_053": "Plan de communication",
        "text_054": "Stratégie digitale",
        "text_055": "Création de supports",
        "text_056": "Mes axes d'amélioration",
        "text_057": "Afin de valider pleinement les compétences de niveau 3 en Business Développement, je dois encore approfondir ma maîtrise des achats complexes en B2B. Mon objectif d'ici la fin de l'année est de mener une négociation complète avec un fournisseur dans le cadre de mon alternance.",
        "text_058": "Compétences Comportementales (Soft Skills)",
        "text_059": "Les qualités humaines qui font la différence au quotidien.",
        "text_060": "Rigueur",
        "text_061": "Sens du relationnel",
        "text_062": "Travail d'équipe",
        "text_063": "Adaptabilité",
        "text_064": "Autonomie",
        "text_065": "Organisation",
        "text_066": "Mon Parcours",
        "text_067": "Analyse de mes expériences professionnelles et académiques selon la méthode attendue pour l'évaluation des compétences (Contexte, Objectifs, Actions, Résultats).",
        "text_068": "Sept 2025 - En cours",
        "text_069": "Attaché Clientèle",
        "text_070": "Crédit Agricole Centre-Est (Alternance)",
        "text_071": "Développer la fidélisation et le rebond commercial en agence, avec une posture de conseil durable.",
        "text_072": "Analyser cette expérience",
        "text_073": "Février 2025",
        "text_074": "Projet Académique : CREASIM",
        "text_075": "Simulation Commerciale (IUT)",
        "text_076": "Construire une stratégie commerciale en équipe sous contrainte de budget et de temps.",
        "text_077": "Fév 2024 - Juin 2025",
        "text_078": "Équipier Polyvalent",
        "text_079": "McDonald's (CDI Étudiant)",
        "text_080": "Garantir un service rapide et conforme aux normes malgré l'intensité des rushs.",
        "text_081": "2021 - 2023",
        "text_082": "Engagements Associatifs",
        "text_083": "Service National Universel (SNU)",
        "text_084": "S'engager sur des missions citoyennes et logistiques avec impact terrain.",
        "text_085": "Formations Académiques",
        "text_086": "IUT Jean Monnet, St-Étienne",
        "text_087": "2023 - Présent",
        "text_088": "Baccalauréat Général",
        "text_089": "Lycée René Descartes (Mention AB)",
        "text_090": "2020 - 2023",
        "text_091": "Crédit Agricole — Analyse réflexive",
        "text_092": "Bloc 1 · Le Cadre",
        "text_093": "Contexte :",
        "text_094": "Alternance en agence, entretiens en face-à-face et appels sortants, travail en binôme avec le conseiller référent.",
        "text_095": "Objectifs &amp; enjeux :",
        "text_096": "Fidéliser les clients et contribuer aux objectifs commerciaux mensuels de l'agence sur l'épargne et l'équipement.",
        "text_097": "Bloc 2 · L'Action",
        "text_098": "J'ai préparé des plans de découverte avant chaque rendez-vous. Ensuite, j'ai utilisé l'OAV pour argumenter les solutions. Enfin, j'ai pratiqué le rebond commercial pour proposer une offre complémentaire cohérente.",
        "text_099": "Bloc 3 · Le Bilan",
        "text_100": "Résultats :",
        "text_101": "+18% de rendez-vous transformés sur 2 mois, retours positifs sur la clarté des explications clients.",
        "text_102": "Difficultés &amp; auto-évaluation :",
        "text_103": "Objections prix sur certains produits ; aujourd'hui, je structurerais davantage mes relances post-rendez-vous et je dois encore progresser sur les ventes croisées complexes.",
        "text_104": "Bloc 4 · Compétences &amp; ressources",
        "text_105": "Ressources mobilisées : R3.02 Entretien de vente, R4.02 Négociation. Compétences BUT validées : « Vendre une offre &amp; manager la relation client » (Niveau 2), « Communiquer l'offre » (Niveau 2).",
        "text_106": "Bloc 5 · Les preuves",
        "text_107": "Capture anonymisée du CRM bancaire",
        "text_108": "Trace des suivis clients et des relances planifiées.",
        "text_109": "Valide la compétence de pilotage de la relation client.",
        "text_110": "Grille de suivi des objectifs agence",
        "text_111": "Comparatif objectifs/réalisations avec indicateurs hebdomadaires.",
        "text_112": "Valide la compétence d'analyse commerciale et de reporting.",
        "text_113": "Projet CREASIM — Analyse réflexive",
        "text_114": "Simulation commerciale en équipe de 5, budget fictif, délais contraints sur 4 semaines.",
        "text_115": "Construire une offre cohérente et défendre des choix stratégiques réalistes face au jury.",
        "text_116": "J'ai coordonné l'équipe sur un planning partagé. D'abord, j'ai analysé le marché ; ensuite, j'ai élaboré la stratégie marketing (ciblage/positionnement) ; puis, j'ai structuré le plan de communication et le pitch final.",
        "text_117": "2e place de la promotion, note orale 16/20, appréciation de la cohérence stratégique.",
        "text_118": "Arbitrages budgétaires complexes ; aujourd'hui je renforcerais l'analyse de sensibilité financière.",
        "text_119": "Ressources mobilisées : R3.04 Études marketing, SAÉ stratégie commerciale, techniques de communication digitale. Compétences BUT validées : marketing (Niveau 2), communication commerciale (Niveau 2), gestion de projet (Niveau 2).",
        "text_120": "PDF de la présentation finale",
        "text_121": "Synthèse du ciblage, positionnement et recommandations.",
        "text_122": "Valide la compétence « communiquer l'offre commerciale ».",
        "text_123": "Excel du budget prévisionnel",
        "text_124": "Tableau des investissements, marges et hypothèses.",
        "text_125": "Valide la compétence d'analyse et de pilotage marketing.",
        "text_126": "Photo d'équipe lors du pitch",
        "text_127": "Moment de soutenance et répartition des rôles à l'oral.",
        "text_128": "Valide la compétence de coordination collective.",
        "text_129": "McDonald's — Analyse réflexive",
        "text_130": "CDI étudiant en restaurant à fort flux, travail en équipe polyvalente.",
        "text_131": "Assurer la satisfaction client immédiate et le respect strict des normes d'hygiène.",
        "text_132": "J'ai organisé les priorités de production pendant les rushs. Ensuite, j'ai coordonné les postes caisse/cuisine. J'ai contrôlé les procédures HACCP et j'ai accompagné les nouveaux équipiers sur les standards.",
        "text_133": "Diminution des temps d'attente observés en pointe, retours clients positifs sur la rapidité.",
        "text_134": "Gestion du stress lors des rushs ; je dois encore gagner en anticipation sur les ruptures produits.",
        "text_135": "Compétences acquises : travail en équipe, résilience, management opérationnel. Ressources IUT mobilisées : communication interpersonnelle, gestion de la qualité de service, techniques de coordination.",
        "text_136": "Planning d'équipe semaine de rush",
        "text_137": "Organisation des postes pour absorber les pics d'activité.",
        "text_138": "Valide la compétence de management opérationnel.",
        "text_139": "Checklist hygiène et sécurité",
        "text_140": "Suivi des contrôles HACCP réalisés en service.",
        "text_141": "Valide la compétence de rigueur process et qualité.",
        "text_142": "SNU — Analyse réflexive",
        "text_143": "Engagement citoyen sur plusieurs événements solidaires et sportifs, interventions en équipe.",
        "text_144": "Assurer une logistique fluide et un accueil qualitatif du public.",
        "text_145": "J'ai planifié la répartition des tâches bénévoles. Ensuite, j'ai géré les flux participants et les stocks terrain. Enfin, j'ai communiqué avec les organisateurs pour ajuster en temps réel.",
        "text_146": "Événements tenus sans incident majeur, feedback positif sur l'accueil.",
        "text_147": "Besoin de mieux anticiper les imprévus météo ; je souhaite structurer davantage mes plans de contingence.",
        "text_148": "Compétences validées : organisation, communication, engagement collectif (Niveau 1 à 2). Ressources mobilisées : techniques d'animation commerciale et gestion événementielle.",
        "text_149": "Photo terrain mission solidaire",
        "text_150": "Illustration des tâches logistiques réalisées avec l'équipe.",
        "text_151": "Valide la compétence d'organisation opérationnelle.",
        "text_152": "Grille d'évaluation d'engagement",
        "text_153": "Retour encadrant sur la posture et la fiabilité.",
        "text_154": "Valide la compétence de collaboration citoyenne.",
        "text_155": "Échangeons",
        "text_156": "Contactez-moi",
        "text_157": "Si mon profil vous intéresse pour une collaboration, une alternance ou un échange, n'hésitez pas à m'envoyer un message.",
        "text_158": "Nom complet",
        "text_159": "Adresse email",
        "text_160": "Message",
        "text_161": "Envoyer le message",
        "text_162": "Portfolio BUT Techniques de Commercialisation - Année 2025",
        "text_163": "LinkedIn",
        "text_164": "&copy;",
        "text_165": "Simon Bonnier. Tous droits réservés.",
        "attr_001": "Ouvrir le menu",
        "attr_002": "Simon Bonnier",
        "attr_003": "Logo Crédit Agricole",
        "attr_004": "Logo McDonald's",
        "attr_005": "Logo Service National Universel",
        "attr_006": "Logo Université Jean Monnet Saint-Étienne",
        "attr_007": "Votre nom",
        "attr_008": "vous@exemple.com",
        "attr_009": "Votre message..."
    },
    "en": {
        "lang_code": "en",
        "cv_link": "img/CV - Simon BONNIER.pdf",
        "form_submit_alert": "Merci ! Dans une version finale, ce formulaire sera relie a une adresse email ou une base de donnees.",
        "text_001": "Simon Bonnier - Portfolio BUT Techniques de Commercialisation",
        "text_002": "S",
        "text_003": ".Bonnier",
        "text_004": "Accueil",
        "text_005": "À propos",
        "text_006": "Compétences",
        "text_007": "Expériences & Projets",
        "text_008": "Contact",
        "text_009": "Bonjour, je suis",
        "text_010": "Simon",
        "text_011": "Bonnier",
        "text_012": "Étudiant en BUT Techniques de Commercialisation",
        "text_013": "Passionné par la relation client, la négociation et la stratégie commerciale. À la recherche de nouveaux défis pour construire un management global et performant.",
        "text_014": "Découvrir mon portfolio",
        "text_015": "Me contacter",
        "text_016": "Parcours",
        "text_017": "BUT Techniques de Commercialisation - 3ème année",
        "text_018": "Spécialisation business développement de la relation client",
        "text_019": "Mon Profil",
        "text_020": "À propos de moi",
        "text_021": "De la théorie à la pratique",
        "text_022": "Actuellement en",
        "text_023": "BUT Techniques de Commercialisation",
        "text_024": "à l'IUT Jean Monnet de Saint-Étienne, j'acquiers une solide expertise en négociation, en gestion de la relation client et en analyse de marchés.",
        "text_025": "Une première expérience en milieu bancaire (Crédit Agricole) m'a offert une vision très concrète des enjeux financiers et économiques, tant pour les entreprises que pour les particuliers. Calme, réfléchi et passionné de sport, j'applique la rigueur et la motivation acquises au quotidien dans mes projets professionnels.",
        "text_026": "Mon Projet Professionnel",
        "text_027": "Mon ambition est d'intégrer un",
        "text_028": "Programme Grande École",
        "text_029": "pour approfondir mes connaissances en stratégie et en finance, et ainsi développer une vision plus globale du management.",
        "text_030": "Télécharger mon CV",
        "text_031": "Localisation",
        "text_032": "Lyon, France",
        "text_033": "Mobilité",
        "text_034": "Permis B",
        "text_035": "Téléphone",
        "text_036": "07 69 48 36 98",
        "text_037": "Email",
        "text_038": "simon.bonnier5@gmail.com",
        "text_039": "Savoir-faire & Savoir-être",
        "text_040": "Mes Compétences",
        "text_041": "Conduire les actions marketing &amp; Participer à la stratégie",
        "text_042": "Analyse de l'environnement, études de marché, élaboration de mix et détection d'opportunités.",
        "text_043": "Analyse de marché",
        "text_044": "Veille concurrentielle",
        "text_045": "Stratégie de positionnement",
        "text_046": "Vendre une offre &amp; Manager la relation client",
        "text_047": "Négociation commerciale, développement de la culture service client, pilotage de la satisfaction.",
        "text_048": "Négociation commerciale",
        "text_049": "Gestion relation client (CRM)",
        "text_050": "Traitement des objections",
        "text_051": "Communiquer l'offre commerciale",
        "text_052": "Structuration de plans de communication, stratégies digitales et création de supports.",
        "text_053": "Plan de communication",
        "text_054": "Stratégie digitale",
        "text_055": "Création de supports",
        "text_056": "Mes axes d'amélioration",
        "text_057": "Afin de valider pleinement les compétences de niveau 3 en Business Développement, je dois encore approfondir ma maîtrise des achats complexes en B2B. Mon objectif d'ici la fin de l'année est de mener une négociation complète avec un fournisseur dans le cadre de mon alternance.",
        "text_058": "Compétences Comportementales (Soft Skills)",
        "text_059": "Les qualités humaines qui font la différence au quotidien.",
        "text_060": "Rigueur",
        "text_061": "Sens du relationnel",
        "text_062": "Travail d'équipe",
        "text_063": "Adaptabilité",
        "text_064": "Autonomie",
        "text_065": "Organisation",
        "text_066": "Mon Parcours",
        "text_067": "Analyse de mes expériences professionnelles et académiques selon la méthode attendue pour l'évaluation des compétences (Contexte, Objectifs, Actions, Résultats).",
        "text_068": "Sept 2025 - En cours",
        "text_069": "Attaché Clientèle",
        "text_070": "Crédit Agricole Centre-Est (Alternance)",
        "text_071": "Développer la fidélisation et le rebond commercial en agence, avec une posture de conseil durable.",
        "text_072": "Analyser cette expérience",
        "text_073": "Février 2025",
        "text_074": "Projet Académique : CREASIM",
        "text_075": "Simulation Commerciale (IUT)",
        "text_076": "Construire une stratégie commerciale en équipe sous contrainte de budget et de temps.",
        "text_077": "Fév 2024 - Juin 2025",
        "text_078": "Équipier Polyvalent",
        "text_079": "McDonald's (CDI Étudiant)",
        "text_080": "Garantir un service rapide et conforme aux normes malgré l'intensité des rushs.",
        "text_081": "2021 - 2023",
        "text_082": "Engagements Associatifs",
        "text_083": "Service National Universel (SNU)",
        "text_084": "S'engager sur des missions citoyennes et logistiques avec impact terrain.",
        "text_085": "Formations Académiques",
        "text_086": "IUT Jean Monnet, St-Étienne",
        "text_087": "2023 - Présent",
        "text_088": "Baccalauréat Général",
        "text_089": "Lycée René Descartes (Mention AB)",
        "text_090": "2020 - 2023",
        "text_091": "Crédit Agricole — Analyse réflexive",
        "text_092": "Bloc 1 · Le Cadre",
        "text_093": "Contexte :",
        "text_094": "Alternance en agence, entretiens en face-à-face et appels sortants, travail en binôme avec le conseiller référent.",
        "text_095": "Objectifs &amp; enjeux :",
        "text_096": "Fidéliser les clients et contribuer aux objectifs commerciaux mensuels de l'agence sur l'épargne et l'équipement.",
        "text_097": "Bloc 2 · L'Action",
        "text_098": "J'ai préparé des plans de découverte avant chaque rendez-vous. Ensuite, j'ai utilisé l'OAV pour argumenter les solutions. Enfin, j'ai pratiqué le rebond commercial pour proposer une offre complémentaire cohérente.",
        "text_099": "Bloc 3 · Le Bilan",
        "text_100": "Résultats :",
        "text_101": "+18% de rendez-vous transformés sur 2 mois, retours positifs sur la clarté des explications clients.",
        "text_102": "Difficultés &amp; auto-évaluation :",
        "text_103": "Objections prix sur certains produits ; aujourd'hui, je structurerais davantage mes relances post-rendez-vous et je dois encore progresser sur les ventes croisées complexes.",
        "text_104": "Bloc 4 · Compétences &amp; ressources",
        "text_105": "Ressources mobilisées : R3.02 Entretien de vente, R4.02 Négociation. Compétences BUT validées : « Vendre une offre &amp; manager la relation client » (Niveau 2), « Communiquer l'offre » (Niveau 2).",
        "text_106": "Bloc 5 · Les preuves",
        "text_107": "Capture anonymisée du CRM bancaire",
        "text_108": "Trace des suivis clients et des relances planifiées.",
        "text_109": "Valide la compétence de pilotage de la relation client.",
        "text_110": "Grille de suivi des objectifs agence",
        "text_111": "Comparatif objectifs/réalisations avec indicateurs hebdomadaires.",
        "text_112": "Valide la compétence d'analyse commerciale et de reporting.",
        "text_113": "Projet CREASIM — Analyse réflexive",
        "text_114": "Simulation commerciale en équipe de 5, budget fictif, délais contraints sur 4 semaines.",
        "text_115": "Construire une offre cohérente et défendre des choix stratégiques réalistes face au jury.",
        "text_116": "J'ai coordonné l'équipe sur un planning partagé. D'abord, j'ai analysé le marché ; ensuite, j'ai élaboré la stratégie marketing (ciblage/positionnement) ; puis, j'ai structuré le plan de communication et le pitch final.",
        "text_117": "2e place de la promotion, note orale 16/20, appréciation de la cohérence stratégique.",
        "text_118": "Arbitrages budgétaires complexes ; aujourd'hui je renforcerais l'analyse de sensibilité financière.",
        "text_119": "Ressources mobilisées : R3.04 Études marketing, SAÉ stratégie commerciale, techniques de communication digitale. Compétences BUT validées : marketing (Niveau 2), communication commerciale (Niveau 2), gestion de projet (Niveau 2).",
        "text_120": "PDF de la présentation finale",
        "text_121": "Synthèse du ciblage, positionnement et recommandations.",
        "text_122": "Valide la compétence « communiquer l'offre commerciale ».",
        "text_123": "Excel du budget prévisionnel",
        "text_124": "Tableau des investissements, marges et hypothèses.",
        "text_125": "Valide la compétence d'analyse et de pilotage marketing.",
        "text_126": "Photo d'équipe lors du pitch",
        "text_127": "Moment de soutenance et répartition des rôles à l'oral.",
        "text_128": "Valide la compétence de coordination collective.",
        "text_129": "McDonald's — Analyse réflexive",
        "text_130": "CDI étudiant en restaurant à fort flux, travail en équipe polyvalente.",
        "text_131": "Assurer la satisfaction client immédiate et le respect strict des normes d'hygiène.",
        "text_132": "J'ai organisé les priorités de production pendant les rushs. Ensuite, j'ai coordonné les postes caisse/cuisine. J'ai contrôlé les procédures HACCP et j'ai accompagné les nouveaux équipiers sur les standards.",
        "text_133": "Diminution des temps d'attente observés en pointe, retours clients positifs sur la rapidité.",
        "text_134": "Gestion du stress lors des rushs ; je dois encore gagner en anticipation sur les ruptures produits.",
        "text_135": "Compétences acquises : travail en équipe, résilience, management opérationnel. Ressources IUT mobilisées : communication interpersonnelle, gestion de la qualité de service, techniques de coordination.",
        "text_136": "Planning d'équipe semaine de rush",
        "text_137": "Organisation des postes pour absorber les pics d'activité.",
        "text_138": "Valide la compétence de management opérationnel.",
        "text_139": "Checklist hygiène et sécurité",
        "text_140": "Suivi des contrôles HACCP réalisés en service.",
        "text_141": "Valide la compétence de rigueur process et qualité.",
        "text_142": "SNU — Analyse réflexive",
        "text_143": "Engagement citoyen sur plusieurs événements solidaires et sportifs, interventions en équipe.",
        "text_144": "Assurer une logistique fluide et un accueil qualitatif du public.",
        "text_145": "J'ai planifié la répartition des tâches bénévoles. Ensuite, j'ai géré les flux participants et les stocks terrain. Enfin, j'ai communiqué avec les organisateurs pour ajuster en temps réel.",
        "text_146": "Événements tenus sans incident majeur, feedback positif sur l'accueil.",
        "text_147": "Besoin de mieux anticiper les imprévus météo ; je souhaite structurer davantage mes plans de contingence.",
        "text_148": "Compétences validées : organisation, communication, engagement collectif (Niveau 1 à 2). Ressources mobilisées : techniques d'animation commerciale et gestion événementielle.",
        "text_149": "Photo terrain mission solidaire",
        "text_150": "Illustration des tâches logistiques réalisées avec l'équipe.",
        "text_151": "Valide la compétence d'organisation opérationnelle.",
        "text_152": "Grille d'évaluation d'engagement",
        "text_153": "Retour encadrant sur la posture et la fiabilité.",
        "text_154": "Valide la compétence de collaboration citoyenne.",
        "text_155": "Échangeons",
        "text_156": "Contactez-moi",
        "text_157": "Si mon profil vous intéresse pour une collaboration, une alternance ou un échange, n'hésitez pas à m'envoyer un message.",
        "text_158": "Nom complet",
        "text_159": "Adresse email",
        "text_160": "Message",
        "text_161": "Envoyer le message",
        "text_162": "Portfolio BUT Techniques de Commercialisation - Année 2025",
        "text_163": "LinkedIn",
        "text_164": "&copy;",
        "text_165": "Simon Bonnier. Tous droits réservés.",
        "attr_001": "Ouvrir le menu",
        "attr_002": "Simon Bonnier",
        "attr_003": "Logo Crédit Agricole",
        "attr_004": "Logo McDonald's",
        "attr_005": "Logo Service National Universel",
        "attr_006": "Logo Université Jean Monnet Saint-Étienne",
        "attr_007": "Votre nom",
        "attr_008": "vous@exemple.com",
        "attr_009": "Votre message..."
    }
};
