module.exports = {
    fr: {
        lang: 'fr',
        page_title: 'Simon Bonnier - Portfolio',
        nav_home: 'Accueil',
        nav_about: 'À propos',
        nav_skills: 'Compétences',
        nav_exp_pro: 'Expériences pro',
        nav_projects: 'Projets & engagements',
        nav_contact: 'Contact',
        mobile_menu_label: 'Ouvrir le menu',
        lang_toggle_label: 'FR / EN',
        hero_intro: 'Bonjour, je suis',
        hero_name_first: 'Simon',
        hero_name_last: 'Bonnier',
        hero_role: 'Étudiant en BUT Techniques de Commercialisation',
        hero_description: 'Passionné par la relation client, la négociation et le développement commercial.',
        hero_cta_primary: 'Découvrir mon parcours',
        hero_cta_secondary: 'Me contacter',
        cv_button: 'Télécharger mon CV',
        cv_link: 'img/CV - Simon BONNIER.pdf',
        profile_title: 'À propos',
        profile_text: "Je construis mon projet professionnel autour de la performance commerciale et d'une relation client durable.",
        skills_title: 'Compétences',
        skills_text: 'Prospection, vente-conseil, communication, analyse de marché et coordination terrain.',
        experiences_title: 'Expériences Professionnelles',
        experiences_intro: 'Mes expériences directement liées au monde professionnel.',
        projects_title: 'Projets & Engagements',
        projects_intro: 'Mes projets académiques et engagements citoyens.',
        ca_date: 'Sept 2025 - En cours',
        ca_title: 'Attaché Clientèle',
        ca_company: 'Crédit Agricole Centre-Est (Alternance)',
        ca_summary: 'Développer la fidélisation client et proposer des solutions bancaires adaptées.',
        mcd_date: '2024 - En cours',
        mcd_title: "Équipier Polyvalent",
        mcd_company: "McDonald's",
        mcd_summary: "Garantir la qualité de service en environnement à forte cadence.",
        creasim_date: 'Février 2025',
        creasim_title: 'Projet CREASIM',
        creasim_company: 'Challenge entrepreneurial',
        creasim_summary: "Construire une recommandation commerciale complète en équipe.",
        snu_date: '2023',
        snu_title: 'Service National Universel (SNU)',
        snu_company: 'Engagement citoyen',
        snu_summary: 'Participer à des missions collectives à impact social et logistique.',
        analyze_button: 'Analyser',
        modal_close: 'Fermer',
        modal_ca_title: 'Analyse · Crédit Agricole',
        modal_ca_text: "Contexte : alternance en agence bancaire. Actions : conseil client, rebond commercial, suivi portefeuille. Résultats : amélioration de la satisfaction et meilleure qualification des besoins.",
        modal_mcd_title: "Analyse · McDonald's",
        modal_mcd_text: "Contexte : service rapide à fort volume. Actions : coordination des postes, respect des normes et gestion des flux. Résultats : meilleure fluidité opérationnelle et service client constant.",
        modal_creasim_title: 'Analyse · Projet CREASIM',
        modal_creasim_text: 'Contexte : projet de simulation commerciale. Actions : étude de marché, argumentaire, présentation finale. Résultats : proposition cohérente et amélioration de la posture commerciale.',
        modal_snu_title: 'Analyse · SNU',
        modal_snu_text: 'Contexte : missions d’engagement collectif. Actions : organisation logistique, coordination et communication. Résultats : événements sécurisés et travail d’équipe renforcé.',
        email_address: 'simon.bonnier5@gmail.com',
        contact_title: 'Contact',
        contact_text: 'Le plus simple est de me contacter directement par email.',
        copy_email_button: 'Copier',
        copied_email_button: 'Copié !',
        footer_text: 'Portfolio - Simon Bonnier'
    },
    en: {
        lang: 'en',
        page_title: 'Simon Bonnier - Portfolio',
        nav_home: 'Home',
        nav_about: 'About',
        nav_skills: 'Skills',
        nav_exp_pro: 'Professional experience',
        nav_projects: 'Projects & commitments',
        nav_contact: 'Contact',
        mobile_menu_label: 'Open menu',
        lang_toggle_label: 'FR / EN',
        hero_intro: 'Hello, I am',
        hero_name_first: 'Simon',
        hero_name_last: 'Bonnier',
        hero_role: 'Bachelor student in Marketing & Sales Techniques',
        hero_description: 'Passionate about customer relationships, negotiation, and business development.',
        hero_cta_primary: 'Explore my background',
        hero_cta_secondary: 'Contact me',
        cv_button: 'Download my resume',
        cv_link: 'img/CV - Simon BONNIER.pdf',
        profile_title: 'About',
        profile_text: 'I build my professional path around sales performance and long-term customer value.',
        skills_title: 'Skills',
        skills_text: 'Prospecting, consultative sales, communication, market analysis, and field coordination.',
        experiences_title: 'Professional Experience',
        experiences_intro: 'My hands-on roles in professional environments.',
        projects_title: 'Projects & Commitments',
        projects_intro: 'My academic projects and civic commitments.',
        ca_date: 'Sep 2025 - Ongoing',
        ca_title: 'Client Advisor',
        ca_company: 'Crédit Agricole Centre-Est (Work-study)',
        ca_summary: 'Develop customer loyalty and provide tailored banking solutions.',
        mcd_date: '2024 - Ongoing',
        mcd_title: 'Crew Member',
        mcd_company: "McDonald's",
        mcd_summary: 'Ensure service quality in a high-paced environment.',
        creasim_date: 'February 2025',
        creasim_title: 'CREASIM Project',
        creasim_company: 'Entrepreneurship challenge',
        creasim_summary: 'Build a complete commercial recommendation as a team.',
        snu_date: '2023',
        snu_title: 'Universal National Service (SNU)',
        snu_company: 'Civic engagement',
        snu_summary: 'Take part in team missions with social and logistical impact.',
        analyze_button: 'Analyze',
        modal_close: 'Close',
        modal_ca_title: 'Analysis · Crédit Agricole',
        modal_ca_text: 'Context: work-study position in a banking branch. Actions: customer advisory, sales follow-up, portfolio monitoring. Results: better satisfaction and clearer needs qualification.',
        modal_mcd_title: "Analysis · McDonald's",
        modal_mcd_text: 'Context: high-volume fast service. Actions: station coordination, standards enforcement, flow management. Results: smoother operations and consistent customer service.',
        modal_creasim_title: 'Analysis · CREASIM Project',
        modal_creasim_text: 'Context: commercial simulation project. Actions: market study, value proposition, final pitch. Results: coherent proposal and improved sales posture.',
        modal_snu_title: 'Analysis · SNU',
        modal_snu_text: 'Context: collective civic missions. Actions: logistics planning, coordination, communication. Results: safe events and stronger teamwork.',
        email_address: 'simon.bonnier5@gmail.com',
        contact_title: 'Contact',
        contact_text: 'The easiest way is to contact me directly by email.',
        copy_email_button: 'Copy',
        copied_email_button: 'Copied!',
        footer_text: 'Portfolio - Simon Bonnier'
    }
};
